"""
Prompt templates for the Research Assistant Agent
"""

QUERY_PLANNING_PROMPT = """
You are a research expert. Given a research topic, generate 3-5 focused search queries that will help gather comprehensive information.

Research Topic: {topic}

Guidelines:
- Create diverse queries covering different aspects
- Include both broad and specific searches
- Focus on credible, factual information
- Avoid redundant queries

Return your response as a Python list of strings, like this:
["query 1", "query 2", "query 3"]

Search Queries:
"""

CONTENT_ANALYSIS_PROMPT = """
You are a content analyst. Analyze the following search results and extract key information.

Search Query: {query}
Search Results: {results}

Extract and organize:
1. Key facts and findings
2. Important statistics or data
3. Expert opinions or quotes
4. Source credibility assessment

Provide your analysis in this JSON format:
{{
    "key_facts": ["fact1", "fact2", "fact3"],
    "statistics": ["stat1", "stat2"],
    "expert_opinions": ["opinion1", "opinion2"],
    "source_quality": "high/medium/low",
    "relevance_score": 8,
    "summary": "Brief summary of findings"
}}

Analysis:
"""

SYNTHESIS_PROMPT = """
You are a research synthesizer. Review all analyzed content and determine what information we have and what gaps remain.

Current Research Topic: {topic}
Analyzed Content: {analyzed_content}
Current Iteration: {iteration}

Tasks:
1. Summarize what we've learned so far
2. Identify information gaps or areas needing more research
3. Determine if research is sufficient or needs continuation

Provide your response in this JSON format:
{{
    "summary": "What we've learned so far",
    "gaps_identified": ["gap1", "gap2"],
    "research_quality": "sufficient/needs_more",
    "confidence_level": 8,
    "next_focus_areas": ["area1", "area2"]
}}

If research_quality is "sufficient" and confidence_level > 7, we'll proceed to report generation.
If iteration >= 3, automatically set research_quality to "sufficient".

Synthesis:
"""

REPORT_GENERATION_PROMPT = """
You are a professional research report writer. Create a comprehensive research report based on all the analyzed information.

Research Topic: {topic}
All Analyzed Content: {analyzed_content}

Create a well-structured report with the following sections:

# Research Report: {topic}

## Executive Summary
[2-3 sentence overview of key findings]

## Key Findings
[Main discoveries and insights]

## Detailed Analysis
[In-depth analysis of the research]

## Supporting Data
[Statistics, facts, and evidence]

## Conclusions
[Summary of implications and takeaways]

## Sources
[List of referenced sources with credibility notes]

---
*Report generated by Research Assistant Agent*

Write the complete report:
"""